// import { Component,OnInit } from '@angular/core';
// import { HttpClient } from '@angular/common/http';
// import { Router } from '@angular/router';
// import { SignupService } from '../signup.service';
// import { FormBuilder } from '@angular/forms';

// @Component({
//   selector: 'app-signup',
//   templateUrl: './signup.component.html',
//   styleUrls: ['./signup.component.css']
// })
// export class SignupComponent implements OnInit {
  
//   constructor(private http: HttpClient,
//     private router:Router,
//      private tata : SignupService,
//     private fb: FormBuilder){}

//   signupUsers:any[] = [];
//   signupobj:any={
//   userName: '',
//   email:'',
//   password: '',
//   confirmPassword:''
//   };
//   ngOnInit(): void {
//     const localData = localStorage.getItem('signupUsers');
//     if(localData!= null){
//       this.signupUsers = JSON.parse(localData);
//     }
//   }
//   onSignUp() 
//   {
//     if (!this.signupobj.userName || !this.signupobj.email || !this.signupobj.password || !this.signupobj.confirmPassword) {
//       alert('Please fill in all fields.');
//       return;
//     }
  
//     if (this.signupobj.password !== this.signupobj.confirmPassword) {
//       alert('Passwords do not match.');
//       return;
//     }
//     const user = {
//       userName: this.signupobj.userName,
//       email: this.signupobj.email,
//       password: this.signupobj.password
//     };
  
//     localStorage.setItem(this.signupobj.email, JSON.stringify(user));
//     alert('Signup successful!');
  
//   }

// }
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { SignupService, Tata } from '../signup.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  signupForm!: FormGroup;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private signupService: SignupService
  ) { }

  ngOnInit(): void {
    this.signupForm = this.fb.group({
      userName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required]
    }, { validator: this.passwordMatchValidator });
  }

  passwordMatchValidator(formGroup: FormGroup) {
    return formGroup.get('password')?.value === formGroup.get('confirmPassword')?.value ? null : { mismatch: true };
  }

  onSignUp() {
    if (this.signupForm.invalid) {
      return;
    }

    const { userName, email, password, confirmPassword } = this.signupForm.value;
    const newUser: Tata = {
      id: 0,  // Assuming id will be generated by the backend
      username: userName,
      email: email,
      password: password,
      confirmpassword: confirmPassword
    };
    
    this.signupService.postItem(newUser).subscribe(
      response => {
        alert('Signup successful!');
        this.router.navigate(['/Add']);
        this.router.navigate(['/login']);
      },
      error => {
        console.error('Error occurred during signup:', error);
        alert('Signup failed. Please try again.');
      }
    );
  }
}
